fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4 # needed for py < 3.8.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        language: node
        language_version: '22.11.0'
        additional_dependencies:
          - eslint@8.36.0
          - typescript@5.0.2
          - prettier@3.0.0
          - '@typescript-eslint/eslint-plugin@5.38.0'
          - '@typescript-eslint/parser@5.38.0'
          - eslint-config-prettier@^8.8.0
          - eslint-plugin-prettier@^5.0.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        language: node
        language_version: '22.11.0'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        language: node
        language_version: '22.11.0'
