fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4 # needed for py < 3.8.1
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: corepack yarn eslint:check
        language: system
        types_or: [ts, tsx]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        language: node
        language_version: '22.11.0'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        language: node
        language_version: '22.11.0'
        args: [
            --disable=MD024 # Multiple headers with the same content
          ]
