fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle
        language_version: python3.6

  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.25.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint-config-prettier@^6.15.0
          - eslint-plugin-prettier@^3.1.4

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
