fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/psf/black
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.23.1
          - typescript@4.3.5
          - prettier@2.7.1
          - '@typescript-eslint/eslint-plugin@5.38.0'
          - '@typescript-eslint/parser@5.38.0'
          - eslint-config-prettier@^8.5.0
          - eslint-plugin-prettier@^4.2.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
