compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: true
nodeLinker: node-modules

packageExtensions:
  '@jupyterlab/services@*':
    dependencies:
      react: '*'
  '@types/react-datepicker@*':
    dependencies:
      react: '*'
      react-dom: '*'
