name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  lint:
    name: Linting (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install JupyterLab
        run: python -m pip install -U jupyterlab~=4.0
      - name: Setup yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install JavaScript dependencies
        run: jlpm install --immutable --mode=skip-build
      - name: Run pre-commit action
        uses: pre-commit/action@v3.0.1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Enable Corepack
        run: corepack enable
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Setup pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-3.9-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.9-
            pip-

      - name: Setup yarn cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install dependencies
        run: python -m pip install -U jupyterlab~=4.0 jupyter_packaging~=0.7.9
      - name: Build the extension
        run: |
          jlpm
          jlpm run eslint:check
          python -m pip install .

          jupyter server extension list 2>&1 | grep -ie "eodag[_-]labextension.*OK"\
            || (jupyter server extension list && exit 1)

          jupyter labextension list 2>&1 | grep -ie "eodag[_-]labextension.*OK"\
            || (jupyter labextension list && exit 1)

          python -m jupyterlab.browser_check
